---
title: "BassDummyAnalysis"
author: "Camille"
date: "2/7/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#check working directory 
getwd()

# load packages
pacman::p_load(ggplot2, knitr, BIOMASS, dplyr, data.table, gdata, 
               rvest, rlang, purrr, tidyverse, iNEXT)

#load data
dummy_plots <- read.csv("bass_dummy_data.csv")
bioclim_data <- 

```

```{r Explore Data}
dim(dummy_plots)
colnames(dummy_plots)

#create df for just trees
dummy_plots_trees <- dummy_plots %>%
  filter(Type_Field != "Liana")%>%
  select(Project, Plot, Grid, TAG_SUM, DBH..mm., Height..meters.)%>%
  mutate(Project2 = Project)%>%
  unite("Project_Plot", Project:Plot)
names(dummy_plots_trees)[4]<- "dbh"
names(dummy_plots_trees)[5]<- "height"

#create liana data


#visually explore data
```

Structure (Abundance and Size Classes)
```{r}


```


AGB Analysis
```{r}
#get wood density
WdDen <- getWoodDensity(genus = dummy_plots_trees$Genus,
          species = dummy_plots_trees$Spp,
          family= dummy_plots_trees$Famille,
          stand = dummy_plots_trees$Project_Plot)

dummy_plots_trees$meanWD <- WdDen$meanWD
dummy_plots_trees$sdWD <- WdDen$sdWD

#calculate AGB for trees
dummy_plots_trees$AGBtree <- computeAGB(D = dummy_plots_trees$dbh, WD = dummy_plots_trees$meanWD, H = dummy_plots_trees$H)

#calculate AGB for lianas


```

Diversity Analysis
```{r}
hill_dat <- data.frame(xtabs(~Project_Plot + Species, data = dummy_plots2))

hill_dat2 <- hill_dat %>% 
  pivot_wider(names_from = "Species", values_from = "Freq")
class(hill_dat2)
hill_dat2_list <- as.list(hill_dat2)

hill_dat3 <- hill_dat %>% 
  pivot_wider(names_from = "NewCode", values_from = "Freq")
hill_dat4 <- hill_dat3[-c(0,1)]
hill_dat4_list <- as.list(hill_dat4)

hill <- iNEXT(hill_dat4_list, q = c(0,1,2), datatype = "abundance")
hill
```

